### ISSUE TITLE
能不能修一下requirements文件

### ISSUE THREAD

**Issue by KevinXuxuxu** [airockchip/rknn-toolkit2#106]
`tensorflow==2.8.1` 现在哪个源应该都不支持了吧，至少都到`2.10.1`了
```
$ pip install -r packages/requirements_cp310-2.1.0.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Collecting protobuf==3.20.3 (from -r packages/requirements_cp310-2.1.0.txt (line 4))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/28/55/b80e8567ec327c060fa39b242392e25690c8899c489ecd7bb65b46b7bb55/protobuf-3.20.3-cp310-cp310-manylinux2014_aarch64.whl (918 kB)
Collecting psutil>=5.9.0 (from -r packages/requirements_cp310-2.1.0.txt (line 7))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/cd/5f/60038e277ff0a9cc8f0c9ea3d0c5eb6ee1d2470ea3f9389d776432888e47/psutil-6.0.0-cp36-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (292 kB)
Collecting ruamel.yaml>=0.17.21 (from -r packages/requirements_cp310-2.1.0.txt (line 8))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/73/67/8ece580cc363331d9a53055130f86b096bf16e38156e33b1d3014fffda6b/ruamel.yaml-0.18.6-py3-none-any.whl (117 kB)
Collecting scipy>=1.9.3 (from -r packages/requirements_cp310-2.1.0.txt (line 9))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/57/b8/ca969a99d34956c6546cbb9ea3f863a387009f68cdbad13cdb07db0cc23d/scipy-1.14.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (35.6 MB)
Collecting tqdm>=4.64.1 (from -r packages/requirements_cp310-2.1.0.txt (line 10))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/48/5d/acf5905c36149bbaec41ccf7f2b68814647347b72075ac0b1fe3022fdc73/tqdm-4.66.5-py3-none-any.whl (78 kB)
Collecting opencv-python>=4.5.5.64 (from -r packages/requirements_cp310-2.1.0.txt (line 11))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/81/e4/7a987ebecfe5ceaf32db413b67ff18eb3092c598408862fff4d7cc3fd19b/opencv_python-4.10.0.84-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (41.7 MB)
Collecting fast-histogram>=0.11 (from -r packages/requirements_cp310-2.1.0.txt (line 12))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/0f/f9/524b8a302862bdc7100a5e0662d3fa49500af20badcabaddeec474819b8d/fast_histogram-0.14-cp39-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (55 kB)
Collecting numpy<=1.26.4 (from -r packages/requirements_cp310-2.1.0.txt (line 13))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/fc/a5/4beee6488160798683eed5bdb7eead455892c3b4e1f78d79d8d3f3b084ac/numpy-1.26.4-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.2 MB)
Collecting onnx==1.14.1 (from -r packages/requirements_cp310-2.1.0.txt (line 16))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/01/76/0b5ed00c6fa265f1979e05aa9e1cf9549cd82b90e6264647d168ec6e0c07/onnx-1.14.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (15.0 MB)
Collecting onnxoptimizer==0.3.8 (from -r packages/requirements_cp310-2.1.0.txt (line 17))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a2/c2/8fcbecf89c52ca3beaccbed4aedb05eb9aa2bf232e18987942b3e1d3f227/onnxoptimizer-0.3.8.tar.gz (18.5 MB)
  Preparing metadata (setup.py) ... done
Collecting onnxruntime==1.16.0 (from -r packages/requirements_cp310-2.1.0.txt (line 18))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/51/d8/7dedff222ac4e4bdccc86bba5cbc7f972a01426af10a1b273328573730fb/onnxruntime-1.16.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (5.6 MB)
Collecting torch<=2.1.0,>=1.13.1 (from -r packages/requirements_cp310-2.1.0.txt (line 19))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/32/87/9c6f150d29efc6125c13e0bb05112183e3e233f574c306354bfa0112d449/torch-2.1.0-cp310-cp310-manylinux2014_aarch64.whl (84.1 MB)
ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement tensorflow==2.8.1 (from versions: 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0, 2.15.1, 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1, 2.17.0)
ERROR: No matching distribution found for tensorflow==2.8.1

[notice] A new release of pip is available: 24.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
```

**Comment by KevinXuxuxu** [comment]
另一个关于onnxoptimizer的问题，跟tensorflow的版本应该是无关的
```
Building wheels for collected packages: onnxoptimizer, h5py
  Building wheel for onnxoptimizer (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [95 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      /mnt/m2/fzxu/projects/rknn/lib/python3.10/site-packages/setuptools/dist.py:478: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'license-file' will not be supported in future
              versions. Please use the underscore name 'license_file' instead.
      
              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      /mnt/m2/fzxu/projects/rknn/lib/python3.10/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_py
      running create_version
      running cmake_build
      -- The C compiler identification is GNU 11.4.0
      -- The CXX compiler identification is unknown
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      CMake Error at CMakeLists.txt:9 (project):
        No CMAKE_CXX_COMPILER could be found.
      
        Tell CMake where to find the compiler by setting either the environment
        variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
        to the compiler, or to the compiler name if it is in the PATH.
      
      
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-6tc7x7pz/onnxoptimizer_ac8e02dab38746c684f08174058999e4/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
      See also "/tmp/pip-install-6tc7x7pz/onnxoptimizer_ac8e02dab38746c684f08174058999e4/.setuptools-cmake-build/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6tc7x7pz/onnxoptimizer_ac8e02dab38746c684f08174058999e4/setup.py", line 320, in <module>
          setuptools.setup(
        File "/mnt/m2/fzxu/projects/rknn/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/mnt/m2/fzxu/projects/rknn/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/mnt/m2/fzxu/projects/rknn/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/mnt/m2/fzxu/projects/rknn/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/mnt/m2/fzxu/projects/rknn/lib/python3.10/site-packages/setuptools/dist.py", line 976, in run_command
          super().run_command(command)
        File "/mnt/m2/fzxu/projects/rknn/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/mnt/m2/fzxu/projects/rknn/lib/python3.10/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/mnt/m2/fzxu/projects/rknn/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/mnt/m2/fzxu/projects/rknn/lib/python3.10/site-packages/setuptools/dist.py", line 976, in run_command
          super().run_command(command)
        File "/mnt/m2/fzxu/projects/rknn/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/mnt/m2/fzxu/projects/rknn/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/mnt/m2/fzxu/projects/rknn/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/mnt/m2/fzxu/projects/rknn/lib/python3.10/site-packages/setuptools/dist.py", line 976, in run_command
          super().run_command(command)
        File "/mnt/m2/fzxu/projects/rknn/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-6tc7x7pz/onnxoptimizer_ac8e02dab38746c684f08174058999e4/setup.py", line 216, in run
          self.run_command('cmake_build')
        File "/mnt/m2/fzxu/projects/rknn/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/mnt/m2/fzxu/projects/rknn/lib/python3.10/site-packages/setuptools/dist.py", line 976, in run_command
          super().run_command(command)
        File "/mnt/m2/fzxu/projects/rknn/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-6tc7x7pz/onnxoptimizer_ac8e02dab38746c684f08174058999e4/setup.py", line 202, in run
          subprocess.check_call(cmake_args)
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/cmake', '-DPython_INCLUDE_DIR=/usr/include/python3.10', '-DPython_EXECUTABLE=/mnt/m2/fzxu/projects/rknn/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DONNX_USE_LITE_PROTO=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-310-aarch64-linux-gnu.so', '-DONNX_OPT_USE_SYSTEM_PROTOBUF=OFF', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-6tc7x7pz/onnxoptimizer_ac8e02dab38746c684f08174058999e4']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onnxoptimizer
  Running setup.py clean for onnxoptimizer
  Building wheel for h5py (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for h5py (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-310
      creating build/lib.linux-aarch64-cpython-310/h5py
      copying h5py/ipy_completer.py -> build/lib.linux-aarch64-cpython-310/h5py
      copying h5py/version.py -> build/lib.linux-aarch64-cpython-310/h5py
      copying h5py/__init__.py -> build/lib.linux-aarch64-cpython-310/h5py
      copying h5py/h5py_warnings.py -> build/lib.linux-aarch64-cpython-310/h5py
      creating build/lib.linux-aarch64-cpython-310/h5py/_hl
      copying h5py/_hl/selections.py -> build/lib.linux-aarch64-cpython-310/h5py/_hl
      copying h5py/_hl/compat.py -> build/lib.linux-aarch64-cpython-310/h5py/_hl
      copying h5py/_hl/dims.py -> build/lib.linux-aarch64-cpython-310/h5py/_hl
      copying h5py/_hl/group.py -> build/lib.linux-aarch64-cpython-310/h5py/_hl
      copying h5py/_hl/datatype.py -> build/lib.linux-aarch64-cpython-310/h5py/_hl
      copying h5py/_hl/vds.py -> build/lib.linux-aarch64-cpython-310/h5py/_hl
      copying h5py/_hl/__init__.py -> build/lib.linux-aarch64-cpython-310/h5py/_hl
      copying h5py/_hl/filters.py -> build/lib.linux-aarch64-cpython-310/h5py/_hl
      copying h5py/_hl/attrs.py -> build/lib.linux-aarch64-cpython-310/h5py/_hl
      copying h5py/_hl/files.py -> build/lib.linux-aarch64-cpython-310/h5py/_hl
      copying h5py/_hl/base.py -> build/lib.linux-aarch64-cpython-310/h5py/_hl
      copying h5py/_hl/dataset.py -> build/lib.linux-aarch64-cpython-310/h5py/_hl
      copying h5py/_hl/selections2.py -> build/lib.linux-aarch64-cpython-310/h5py/_hl
      creating build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_file.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_file_alignment.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_datatype.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_file_image.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/conftest.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_h5.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_group.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_slicing.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_completions.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_attrs.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_file2.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_dtype.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_dataset_getitem.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_dataset.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_h5z.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_h5f.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_filters.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/__init__.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_big_endian_file.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_attrs_data.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_dimension_scales.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_dataset_swmr.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_h5p.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_errors.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_h5d_direct_chunk.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_dims_dimensionproxy.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/common.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_h5pl.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_selections.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_attribute_create.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_base.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_objects.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_h5o.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_ros3.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      copying h5py/tests/test_h5t.py -> build/lib.linux-aarch64-cpython-310/h5py/tests
      creating build/lib.linux-aarch64-cpython-310/h5py/tests/data_files
      copying h5py/tests/data_files/__init__.py -> build/lib.linux-aarch64-cpython-310/h5py/tests/data_files
      creating build/lib.linux-aarch64-cpython-310/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_lowlevel_vds.py -> build/lib.linux-aarch64-cpython-310/h5py/tests/test_vds
      copying h5py/tests/test_vds/__init__.py -> build/lib.linux-aarch64-cpython-310/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_highlevel_vds.py -> build/lib.linux-aarch64-cpython-310/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_virtual_source.py -> build/lib.linux-aarch64-cpython-310/h5py/tests/test_vds
      copying h5py/tests/data_files/vlen_string_dset_utc.h5 -> build/lib.linux-aarch64-cpython-310/h5py/tests/data_files
      copying h5py/tests/data_files/vlen_string_s390x.h5 -> build/lib.linux-aarch64-cpython-310/h5py/tests/data_files
      copying h5py/tests/data_files/vlen_string_dset.h5 -> build/lib.linux-aarch64-cpython-310/h5py/tests/data_files
      running build_ext
      Building h5py requires pkg-config unless the HDF5 path is explicitly specified using the environment variable HDF5_DIR. For more information and details, see https://docs.h5py.org/en/stable/build.html#custom-installation
      error: pkg-config probably not installed: FileNotFoundError(2, 'No such file or directory')
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h5py
Failed to build onnxoptimizer h5py
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (onnxoptimizer, h5py)
```

**Comment by KevinXuxuxu** [comment]
换成推荐的Python 3.8也没用，都是一样的错误

**Comment by suse-chen** [comment]
问题解决了吗？

**Comment by WilliamGrant** [comment]
对我也遇到了这个onnxoptimizer版本问题，我都已经安装了rknn-toolkit2==2.3.0 还在提示下载安装

```
#9 333.7 Collecting onnxoptimizer==0.2.7
#9 333.9   Downloading onnxoptimizer-0.2.7.tar.gz (16.8 MB)
#9 362.0     ERROR: Command errored out with exit status 1:
#9 362.0      command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2xj4qxe8/onnxoptimizer_51d59eadc6c04f65affd86accf69080f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2xj4qxe8/onnxoptimizer_51d59eadc6c04f65affd86accf69080f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dvb9c_7p
#9 362.0          cwd: /tmp/pip-install-2xj4qxe8/onnxoptimizer_51d59eadc6c04f65affd86accf69080f/
#9 362.0     Complete output (5 lines):
#9 362.0     Traceback (most recent call last):
#9 362.0       File "<string>", line 1, in <module>
#9 362.0       File "/tmp/pip-install-2xj4qxe8/onnxoptimizer_51d59eadc6c04f65affd86accf69080f/setup.py", line 75, in <module>
#9 362.0         assert CMAKE, 'Could not find "cmake" executable!'
#9 362.0     AssertionError: Could not find "cmake" executable!
#9 362.0     ----------------------------------------
#9 362.0 WARNING: Discarding https://files.pythonhosted.org/packages/a3/56/b7c3af61c87d565c4721c6d33b50fcc007c3545b1c5ffd118023ed342197/onnxoptimizer-0.2.7.tar.gz#sha256=a9f972b2b68ceb82b1f268042879f807fceb9ad76e38def2a39f102e62216d21 (from https://pypi.org/simple/onnxoptimizer/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#9 362.0 INFO: pip is looking at multiple versions of onnx to determine which version is compatible with other requirements. This could take a while.
#9 362.0 INFO: pip is looking at multiple versions of ultralytics to determine which version is compatible with other requirements. This could take a while.
#9 362.0 INFO: pip is looking at multiple versions of paddlepaddle to determine which version is compatible with other requirements. This could take a while.
#9 362.0 INFO: pip is looking at multiple versions of paddleocr to determine which version is compatible with other requirements. This could take a while.
#9 362.0 INFO: pip is looking at multiple versions of opencv-python-headless to determine which version is compatible with other requirements. This could take a while.
#9 362.0 INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
#9 362.0 INFO: pip is looking at multiple versions of torch to determine which version is compatible with other requirements. This could take a while.
#9 362.0 ERROR: Could not find a version that satisfies the requirement onnxoptimizer==0.2.7 (from rknn-toolkit2) (from versions: 0.2.7, 0.3.0, 0.3.1, 0.3.2, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.3.11, 0.3.12, 0.3.13)
#9 362.0 ERROR: No matching distribution found for onnxoptimizer==0.2.7
#9 364.4 WARNING: You are using pip version 21.1.3; however, version 24.3.1 is available.
#9 364.4 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
#9 ERROR: process "/dev/.buildkit_qemu_emulator /bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1
```
