### ISSUE TITLE
能否支持cpu版本呢？

### ISSUE THREAD

**Issue by NimbleKun** [airockchip/rknn-toolkit2#111]
Traceback (most recent call last):
  File "./test.py", line 8, in <module>
    from rknn.api import RKNN
  File "/home/hinson/.local/lib/python3.8/site-packages/rknn/api/__init__.py", line 1, in <module>
    from rknn.api.rknn import RKNN
  File "/home/hinson/.local/lib/python3.8/site-packages/rknn/api/rknn.py", line 6, in <module>
    from .rknn_platform import get_host_os_platform, get_librknn_api_require_dll_dir
  File "rknn/api/rknn_platform.py", line 9, in init rknn.api.rknn_platform
  File "rknn/api/rknn_utils.py", line 8, in init rknn.api.rknn_utils
  File "/home/hinson/.local/lib/python3.8/site-packages/torch/__init__.py", line 290, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcudnn.so.9: cannot open shared object file: No such file or directory

**Comment by yuyun2000** [comment]
这个似乎你的自己的torch环境的问题
