### ISSUE TITLE
Accuracy analysis failed!

### ISSUE THREAD

**Issue by LongDan15** [airockchip/rknn-toolkit2#112]
I target set by user is: rk3566
I Get hardware info: target_platform = rk3566, os = Linux, aarch = aarch64
I Check RK3566 board npu runtime version
I Starting ntp or adb, target is RK3566
I Start adb...
I Connect to Device success!
I NPUTransfer: Starting NPU Transfer Client, Transfer version 2.1.0 (b5861e7@2020-11-23T11:50:36)
D RKNNAPI: ==============================================
D RKNNAPI: RKNN VERSION:
D RKNNAPI:   API: 2.0.0b0 (18eacd0 build@2024-03-22T06:07:59)
D RKNNAPI:   DRV: rknn_server: 2.0.0b0 (18eacd0 build@2024-03-22T14:07:19)
D RKNNAPI:   DRV: rknnrt: 2.0.0b0 (35a6907d79@2024-03-24T10:31:14)
D RKNNAPI: ==============================================
D RKNNAPI: Input tensors:
D RKNNAPI:   index=0, name=data, n_dims=4, dims=[1, 112, 112, 3], n_elems=37632, size=37632, w_stride = 0, size_with_stride = 0, fmt=NHWC, type=INT8, qnt_type=AFFINE, zp=0, scale=0.007843
D RKNNAPI: Output tensors:
D RKNNAPI:   index=0, name=554, n_dims=2, dims=[1, 512], n_elems=512, size=512, w_stride = 0, size_with_stride = 0, fmt=UNDEFINED, type=INT8, qnt_type=AFFINE, zp=-38, scale=0.044667
adb: unable to connect for root: closed
adb: error: remote object '/userdata/dumps' does not exist
mv: 无法获取'./snapshot/runtime/dumps' 的文件状态(stat): 没有那个文件或目录
E accuracy_analysis: Catch exception when accuracy_analysis: FileNotFoundError(2, 'No such file or directory')
E accuracy_analysis: Traceback (most recent call last):
E accuracy_analysis:   File "rknn/api/rknn_base.py", line 2914, in rknn.api.rknn_base.RKNNBase.accuracy_analysis
E accuracy_analysis:   File "rknn/api/rknn_base.py", line 2852, in rknn.api.rknn_base.RKNNBase._runtime_dump
E accuracy_analysis: FileNotFoundError: [Errno 2] No such file or directory: './snapshot/runtime/npy'
W If you can't handle this error, please try updating to the latest version of the toolkit2 and runtime from:
  https://console.zbox.filez.com/l/I00fc3 (Pwd: rknn)  Path: RKNPU2_SDK / 2.X.X / develop /
  If the error still exists in the latest version, please collect the corresponding error logs and the model,
  convert script, and input data that can reproduce the problem, and then submit an issue on:
  https://redmine.rock-chips.com (Please consult our sales or FAE for the redmine account)

**Comment by Mr-MoNET** [comment]
我靠，老哥，我跟你遇到一个一模一样的问题；请问解决了吗？

![Screenshot from 2024-08-16 14-39-31](https://github.com/user-attachments/assets/f14577e3-ed43-4590-b5d7-037ffc5f94d6)
