### ISSUE TITLE
build的时候clip算子报错：const [with T = float] min->Shape().IsScalar() was false. min should be a scalar.

### ISSUE THREAD

**Issue by blueWatermelonFri** [airockchip/rknn-toolkit2#114]
在rk3588模拟器对模型做量化的时候报错：
```
--> Building model
2024-08-14 16:24:58.762700412 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Clip node. Name:'custom_added_Clip0' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/clip.cc:107 void onnxruntime::Clip::ComputeImpl<T>::operator()(const onnxruntime::Tensor*, const onnxruntime::Tensor*, const onnxruntime::Tensor*, onnxruntime::Tensor*, onnxruntime::concurrency::ThreadPool*) const [with T = float] min->Shape().IsScalar() was false. min should be a scalar.

E build: Catch exception when building RKNN model!
E build: Traceback (most recent call last):
E build:   File "rknn/api/rknn_base.py", line 1977, in rknn.api.rknn_base.RKNNBase.build
E build:   File "rknn/api/graph_optimizer.py", line 884, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
E build:   File "rknn/api/session.py", line 149, in rknn.api.session.Session.run
E build:   File "/home/heyuanhong/miniconda3/envs/toolkit2/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
E build:     return self._sess.run(output_names, input_feed, run_options)
E build: onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Clip node. Name:'custom_added_Clip0' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/clip.cc:107 void onnxruntime::Clip::ComputeImpl<T>::operator()(const onnxruntime::Tensor*, const onnxruntime::Tensor*, const onnxruntime::Tensor*, onnxruntime::Tensor*, onnxruntime::concurrency::ThreadPool*) const [with T = float] min->Shape().IsScalar() was false. min should be a scalar.
```
发现是`clip`算子报错，后来我把clip算子的维度从[1,1,1,1]改为[1]后就不报错了，是rknn3588不支持clip算子的维度是多维的吗？

**Comment by yuyun2000** [comment]
先看算子文档说明，如果写的无限制就是rk自己的bug

**Comment by blueWatermelonFri** [comment]
我看过算子文档了，写的是无限制。

**Comment by yuyun2000** [comment]
那就是rk自己的问题，放心，这种问题很多。 不过我看你这是onnxruntime报的错，你pc可以正常推理吗？端侧onnxruntime的版本呢

**Comment by blueWatermelonFri** [comment]
刚刚查阅了onnx的算子手册，是我的问题，因为clip算子只支持标量，我加上clip算子的时候人为的把它变成张量了。
