### ISSUE TITLE
使用连扳推理报错

### ISSUE THREAD

**Issue by xiefeihua** [airockchip/rknn-toolkit2#131]
I target set by user is: rk3566
D adb path: /home/friva/.local/lib/python3.10/site-packages/rknn/3rdparty/platform-tools/adb/linux-x86_64/adb
I Get hardware info: target_platform = rk3566, os = Linux, aarch = aarch32
I Check RK3566 board npu runtime version
I Starting ntp or adb, target is RK3566
I Start adb...
adb: error: cannot bind listener: attempted to listen on unavailable socket type: localabstract:transfer_proxy
E init_runtime: Connect to Device (58299137ef51f80d) Failure (-2), Please check the USB or network connection!
E init_runtime: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2412, in rknn.api.rknn_base.RKNNBase.init_runtime
  File "rknn/api/rknn_runtime.py", line 219, in rknn.api.rknn_runtime.RKNNRuntime.__init__
  File "rknn/api/rknn_platform.py", line 372, in rknn.api.rknn_platform.start_ntp_or_adb
Exception: Init runtime environment failed!

I ===================== WARN(0) =====================
E rknn-toolkit2 version: 2.1.0+708089d1

**Comment by xiefeihua** [comment]
我单独使用adb 是可以正常连接上得

**Comment by yuyun2000** [comment]
更新以下rknnserver试试
