### ISSUE TITLE
Convert ASR encoder from onnx to rknn got 3 different errors The shape of '/Unsqueeze_output_0' is (1, 0), it is abnormal! The input 1 of Range('/Range') need to be constant! The input tensor cannot be reshaped

### ISSUE THREAD

**Issue by Kracozebr** [airockchip/rknn-toolkit2#136]
I'm trying to export an encoder for ASR model from onnx to rknn.
There is my code:
```
import os
import traceback
import time
import sys
import numpy as np
import cv2
from rknn.api import RKNN

ONNX_MODEL = 'models/onnx/encoder.onnx'
RKNN_MODEL = 'models/rknn/encoder.rknn'



if __name__ == '__main__':

    # Create RKNN object
    rknn = RKNN(verbose=True)

    # If model does not exist exit
    if not os.path.exists(ONNX_MODEL):
        print('Where is no moel in path {}'.format(ONNX_MODEL))
        sys.exit(1)

    # pre-process config
    print('--> config model')
    dynamic_input=[[[1,300,80], [1]],  [[1,400,80], [1]], [[1,500,80], [1]]]
    rknn.config( target_platform='rk3588', dynamic_input=dynamic_input)
    print('done')

    # Load model
    print('--> Loading model')
    # input_size_list = [[1, 500, 80], [1]]
    # ret = rknn.load_onnx(model=ONNX_MODEL,  input_size_list=input_size_list) #inputs=["x", "x_lens"],

    ret = rknn.load_onnx(model=ONNX_MODEL)
    if ret != 0:
        print('Load model failed!')
        exit(ret)
    print('done')


```

But I got the next error:
```
I rknn-toolkit2 version: 2.1.0+708089d1
--> config model
W config: Please make sure the model can be dynamic when enable 'config.dynamic_input'!
I The 'dynamic_input' function has been enabled, the MaxShape is dynamic_input[2] = [[1, 500, 80], [1]]!
          The following functions are subject to the MaxShape:
            1. The quantified dataset needs to be configured according to MaxShape
            2. The eval_perf or eval_memory return the results of MaxShape
done
--> Loading model

I Loading : 100%|██████████████████████████████████████████████| 717/717 [00:00<00:00, 15659.11it/s]
W load_onnx: The config.mean_values is None, zeros will be set for input 0!
W load_onnx: The config.std_values is None, ones will be set for input 0!
done
--> Building model
W build: The dataset='./dataset.txt' is ignored because do_quantization = False!
D base_optimize ...
D base_optimize done.
D 
D fold_constant ...
I    FoldConstant :   1%|▏                                       | 31/5225 [00:00<00:18, 282.01it/s]E build: The shape of '/Unsqueeze_output_0' is (1, 0), it is abnormal!
W build: ===================== WARN(4) =====================
E rknn-toolkit2 version: 2.1.0+708089d1
I    FoldConstant :   1%|▌                                       | 69/5225 [00:00<00:13, 394.65it/s]
E build: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 1889, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/graph_optimizer.py", line 1023, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: The shape of '/Unsqueeze_output_0' is (1, 0), it is abnormal!

I ===================== WARN(0) =====================
E rknn-toolkit2 version: 2.1.0+708089d1
Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 1889, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/graph_optimizer.py", line 1023, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: The shape of '/Unsqueeze_output_0' is (1, 0), it is abnormal!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 43, in <module>
    ret = rknn.build(do_quantization=False, dataset='./dataset.txt')
  File "/usr/local/lib/python3.8/dist-packages/rknn/api/rknn.py", line 192, in build
    return self.rknn_base.build(do_quantization=do_quantization, dataset=dataset, expand_batch_size=rknn_batch_size)
  File "rknn/api/rknn_log.py", line 314, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 1889, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/graph_optimizer.py", line 1023, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: The shape of '/Unsqueeze_output_0' is (1, 0), it is abnormal!
```

How to fix it? The onnx model is working I test it, so the bug during convertation.

I tried to convert without dynamic shape:
```
 rknn.config( target_platform='rk3588')
 input_size_list = [[1, 500, 80], [1]]
 ret = rknn.load_onnx(model=ONNX_MODEL, inputs=["x", "x_lens"], input_size_list=input_size_list)
```

But got another error:
```
I rknn-toolkit2 version: 2.1.0+708089d1
--> config model
done
--> Loading model
W load_onnx: If you don't need to crop the model, don't set 'inputs'/'input_size_list'/'outputs'!
I Loading : 100%|██████████████████████████████████████████████| 717/717 [00:00<00:00, 14269.05it/s]
W load_onnx: The config.mean_values is None, zeros will be set for input 0!
W load_onnx: The config.std_values is None, ones will be set for input 0!
done
--> Building model
W build: The dataset='./dataset.txt' is ignored because do_quantization = False!
D base_optimize ...
D base_optimize done.
D 
D fold_constant ...
I    FoldConstant :   0%|                                                  | 0/5225 [00:00<?, ?it/s]E build: The input 1 of Range('/Range') need to be constant! It will cause the graph to be a dynamic graph!
                  Remove Range('/Range') manually and try again!
W build: ===================== WARN(4) =====================
E rknn-toolkit2 version: 2.1.0+708089d1
I    FoldConstant :   1%|▌                                       | 68/5225 [00:00<00:07, 689.69it/s]
E build: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 1889, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/graph_optimizer.py", line 903, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
  File "rknn/api/graph_optimizer.py", line 366, in rknn.api.graph_optimizer._dynamic_check
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: The input 1 of Range('/Range') need to be constant! It will cause the graph to be a dynamic graph!
                  Remove Range('/Range') manually and try again!

I ===================== WARN(0) =====================
E rknn-toolkit2 version: 2.1.0+708089d1
Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 1889, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/graph_optimizer.py", line 903, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
  File "rknn/api/graph_optimizer.py", line 366, in rknn.api.graph_optimizer._dynamic_check
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: The input 1 of Range('/Range') need to be constant! It will cause the graph to be a dynamic graph!
                  Remove Range('/Range') manually and try again!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 44, in <module>
    ret = rknn.build(do_quantization=False, dataset='./dataset.txt')
  File "/usr/local/lib/python3.8/dist-packages/rknn/api/rknn.py", line 192, in build
    return self.rknn_base.build(do_quantization=do_quantization, dataset=dataset, expand_batch_size=rknn_batch_size)
  File "rknn/api/rknn_log.py", line 314, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 1889, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/graph_optimizer.py", line 903, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
  File "rknn/api/graph_optimizer.py", line 366, in rknn.api.graph_optimizer._dynamic_check
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: The input 1 of Range('/Range') need to be constant! It will cause the graph to be a dynamic graph!
                  Remove Range('/Range') manually and try again!

```

After that I tried to export to onnx model with no dynamic shapes, and I got the other error:
```
I rknn-toolkit2 version: 2.1.0+708089d1
--> config model
done
--> Loading model
W load_onnx: If you don't need to crop the model, don't set 'inputs'/'input_size_list'/'outputs'!
I Loading : 100%|██████████████████████████████████████████████| 717/717 [00:00<00:00, 12963.74it/s]
W load_onnx: The config.mean_values is None, zeros will be set for input 0!
W load_onnx: The config.std_values is None, ones will be set for input 0!
done
--> Building model
W build: The dataset='./dataset.txt' is ignored because do_quantization = False!
D base_optimize ...
D base_optimize done.
D 
D fold_constant ...
I    FoldConstant :   1%|▎                                       | 46/5392 [00:00<00:11, 453.80it/s]2024-08-30 07:29:55.961542217 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Reshape node. Name:'/encoder_embed/Reshape' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:44 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,246,128,19}, requested shape:{1,46,2432}

I    FoldConstant :   1%|▍                                       | 64/5392 [00:00<00:13, 383.70it/s]
E build: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 1889, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/graph_optimizer.py", line 973, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
  File "rknn/api/session.py", line 150, in rknn.api.session.Session.run
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/encoder_embed/Reshape' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:44 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,246,128,19}, requested shape:{1,46,2432}


W build: ===================== WARN(4) =====================
E rknn-toolkit2 version: 2.1.0+708089d1
Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 1889, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/graph_optimizer.py", line 973, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
  File "rknn/api/session.py", line 150, in rknn.api.session.Session.run
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/encoder_embed/Reshape' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:44 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,246,128,19}, requested shape:{1,46,2432}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 45, in <module>
    ret = rknn.build(do_quantization=False, dataset='./dataset.txt')
  File "/usr/local/lib/python3.8/dist-packages/rknn/api/rknn.py", line 192, in build
    return self.rknn_base.build(do_quantization=do_quantization, dataset=dataset, expand_batch_size=rknn_batch_size)
  File "rknn/api/rknn_log.py", line 314, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 1889, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/graph_optimizer.py", line 973, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
  File "rknn/api/session.py", line 150, in rknn.api.session.Session.run
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/encoder_embed/Reshape' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:44 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,246,128,19}, requested shape:{1,46,2432}
```

**Comment by zen-xingle** [comment]
The '/Range' op will case it to dynamic shape model refer to the input lens.

This means it's a real dynamic shape model, but not a multi-fix-shape model that RKNN supports. Please try to remove /Range op first.

**Comment by xiangzhangpang** [comment]
i also try to convert asr onnx to rkkn,get  3  errors that same with yours,are you fixed?

**Comment by alex-di-96** [comment]
I'm hitting the same class of problem converting ASR encoders to RKNN (rknn-toolkit2 2.3.2, `target_platform=rk3576`) and wanted to add two independent data points, since this issue has been open a while.

**Case A: T-Bank's T-one (`t-tech/T-one` on HuggingFace)**, a streaming Conformer-CTC ASR model. `rknn.build()` succeeds (`build ret: 0`, `export ret: 0`, `do_quantization=False`), but inference produces incorrect output — confirmed via a three-way comparison on identical real audio input:
- Plain onnxruntime on the source ONNX graph: correct transcription.
- RKNN PC simulator (`init_runtime(target=None)`) on the converted graph: garbage output (collapses to a single repeated token).
- Real RK3576 hardware: same garbage output, plus a runtime error on every inference call:
  ```
  E RKNN: failed to submit!, op id: 33, op name: Slice:/Unsqueeze_output_0_slice#1, flags: 0x5, task start: 37823, task number: 46, run task counter: 7, int status: 0
  ```

This model threads a streaming state tensor through the graph (state shape `(1, 219729)` float16, one 2400-sample/300ms chunk per call). The failing op sits right where the incoming state gets combined with new input via `Concat -> Unsqueeze -> Cast -> Conv`, near the very start of the graph (op id 33 out of ~1545 total). Reordering the `Cast`/`Unsqueeze` at that site (casting to float32 before unsqueezing instead of after) did not resolve it, so the bug is deeper than op ordering at that specific location.

Also tried the `op_target` config option to force the offending op to CPU by name — it turns out none of the original ONNX `Slice`/`Unsqueeze` node names survive as valid `op_target` keys by the time `build()` runs: every one of 224 candidate node names across the encoder was rejected with `Invalid key of '...' in 'op_target'!`, even names that pass `load_onnx()`'s own validation fine. They appear to get fused/renamed internally before `build()`'s check happens, which makes per-op CPU targeting impractical for this Slice/Unsqueeze pattern without knowing RKNN's internal post-fusion names.

**Case B: an ASR encoder exported via onnxruntime's transformer-fusion optimizer** (producing `com.microsoft` contrib ops like `SkipLayerNormalization`/`BiasGelu` with empty-string optional output names). `rknn.build()`'s `fold_constant` stage crashed with `Could not find OrtValue with name ''`. Root-caused to those empty optional-output names; fixed by de-fusing back to plain `Add`+`LayerNormalization` and `Add`+erf-based `Gelu` (`0.5*x*(1+erf(x/sqrt(2)))`, since opset 18 has no standard fused `Gelu`) before conversion. That gets past `fold_constant`, but the next stage (`correct_ops`) then crashes with a bare `IndexError: list index out of range`, no node identified in the trace — same general fragility this issue is about, just a different crash site.

Happy to share minimal repro details for either case if it's useful for tracking this down.
