### ISSUE TITLE
Onnx model conversion fails with "E build: Invalid w_par['dtype'] = float16 for /encoder/0/tdf/0/Transpose_output_0!"

### ISSUE THREAD

**Issue by Sermus** [airockchip/rknn-toolkit2#144]
Hello,
I'm trying to convert an onnx model to rknn with a script below:

  ```
import numpy as np
  from rknn.api import RKNN
  
  ONNX_MODEL = 'nets/3_quantized/qat_quantized_int8.onnx'
  RKNN_MODEL = 'qat_quantized_int8_rv1103.rknn'
  
  if __name__ == '__main__':
      rknn = RKNN(verbose=True)
  
      # pre-process config
      print('--> config model')
      rknn.config(target_platform='rv1106',  optimization_level=0, remove_reshape=True, model_pruning=True)
      print('done')
  
      ret = rknn.load_onnx(model=ONNX_MODEL,input_size_list=[[1,4,128,2048]])
      if ret != 0:
          print('Load model failed!')
          exit(ret)
      print('done')
  
      # Build model
      print('--> Building model')
      ret = rknn.build(do_quantization=False, rknn_batch_size=1)
      if ret != 0:
          print('Build model failed!')
          exit(ret)
      print('done')
  
      # Export rknn model
      print('--> Export rknn model')
      ret = rknn.export_rknn(RKNN_MODEL)
      if ret != 0:
          print('Export rknn model failed!')
          exit(ret)
      print('done')
  
  
      rknn.release()
```

The process fails with the output below at the end of the log:
E build: Invalid w_par['dtype'] = float16 for /encoder/0/tdf/0/Transpose_output_0!
W build: ===================== WARN(2) =====================
E rknn-toolkit2 version: 2.1.0+708089d1
E build: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 1937, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/quant_utils.py", line 604, in rknn.api.quant_utils.compute_param
  File "rknn/api/quant_utils.py", line 230, in rknn.api.quant_utils.cal_bias
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Invalid w_par['dtype'] = float16 for /encoder/0/tdf/0/Transpose_output_0!

I ===================== WARN(0) =====================
E rknn-toolkit2 version: 2.1.0+708089d1

The same model is converted successfully with rknn-toolkit2 1.6.0.
The same model but in tflite also successfully converts.

**Comment by zen-xingle** [comment]
Since there is still no unified standard for the QAT function of ONNX, it is recommended that users directly feed the original QAT model instead of converting to the ONNX model and feed ONNX model to RKNN.

**Comment by Sermus** [comment]
Thanks, zen-xingle. Onnx is the native format in this case. The model was quantized in a 3rdparty framework that exports model to onnx and couple of other formats including tflite. Is there a recommendation for what usually works best as input format for rknn?
