### ISSUE TITLE
A model converts successfully for rv1106 but inference fails

### ISSUE THREAD

**Issue by Sermus** [airockchip/rknn-toolkit2#145]
Hello,
I converted one of my models from tflite to rknn with rknn-toolkit2@2.1.0.
However, when I try to infer it in rv1106 I get this error:

> E RKNN: unsupport cpu Transpose op, op name: Transpose:input.1_155:out0__104 in current, please try updating to the latest version of the toolkit2 and runtime from: https://console.zbox.filez.com/l/I00fc3 (PWD: rknn)
> E RKNN: rknn fallback cpu failed
> rknn_init fail! ret=-1
> init_vocals_model fail! ret=-1 model_path=model/acuity_quantized_rv1106.rknn

The conversion log is as follows:
[convert.log](https://github.com/user-attachments/files/16920172/convert.log)

**Comment by chifredhong** [comment]
I find two reasons. First, float16 precision is not supported in rv1106, did you use hybrid quantization? Second, transpose shape (1,32,128,2048), 128*2048 has exceeded the limit of hardware.

**Comment by Sermus** [comment]
Hi Chifredhong,
Thanks for your comment. I have several questions/notes as a follow-up:
1) No, I didn't do quantization. The original TFLite network was QAT, so I hoped it would be converted to RKNN without additional quantization.
2) The conversion was done for rv1106 as a target. Now, I see some FP operations are scheduled for the NPU. Shouldn't it have failed during conversion with an explicit explanation that FP is not supported by the NPU?
3) Can I schedule the FP operations back for the CPU?
4) For the transpose operation, what's the limit of the NPU?
5) If the op exceeds the limit, can I assign the operation to the CPU?

BR,
Andrey.

**Comment by yuyun2000** [comment]
https://github.com/airockchip/rknn-toolkit2/blob/master/doc/05_RKNN_Compiler_Support_Operator_List_V2.1.0.pdf  
See the documentation for details on the operator.

**Comment by qing0326** [comment]
I encountered the same problem as well. May I ask if you have resolved it? How did you solve it? I really need your help.

**Comment by walletiger** [comment]
遇到类似的问题，rv1106 下已经是2.3的 runtime　库　librknnmrt version: 2.3.0 (c949ad889d@2024-11-07T11:37:43)
模型转换成功，执行时提示:
E RKNN: unsupport cpu exNorm op, op name: exNorm:p2o.ReduceMean.0_2ln in current, please try updating to the latest version of the toolkit2 and runtime from: https://console.zbox.filez.com/l/I00fc3 (PWD: 
rknn)
E RKNN: rknn fallback cpu failed

**Comment by 408550969** [comment]
@walletiger 这个问题解决了吗

**Comment by bitnboson** [comment]
Hi, me too having same problem but on rv1103, with rknn-toolkit2 version 2.3.2
I am trying to use fastDepth int8 quantized tflite model to run on luckfox pico rv1103.

Here are the log on rock_server
```
743046768 SERVER RKNPUZCRuntime(20): Create RKNN runtime!
-1271292278 SERVER init(116): Init RKNN runtime!
E RKNN: unsupport cpu Transpose op, op name: Transpose:StatefulPartitionedCall:0_int8_prequant__738 in current, please try updating to the latest version of the toolkit2 and runtime from: https://console.zbox.filez.com/l/I00fc3 (PWD: rknn)
E RKNN: rknn fallback cpu failed
-1271292278 SERVER init(178): rknn_init fail! ret=-1
-1060838305 SERVER process_msg_init(254): Client 0 init model fail!
-1060838345 SERVER process_msg_init(263): send MSG_INIT_ACK success!
206175856 SERVER recvTask(35): client may close! client id=0
-65902643 SERVER ~RKNPUZCRuntime(33): Unload RKNN runtime!
-787457149 SERVER deinit(198): Deinit RKNN runtime!
1550501810 SERVER processMsg(1222): Close client 0!
```
 
Here is the log from python script trying to run that model with rv1103 as execution target
```
D RKNNAPI: ==============================================
D RKNNAPI: RKNN VERSION:
D RKNNAPI:   API: 2.3.2 (1842325 build@2025-03-30T09:55:23)
D RKNNAPI:   DRV: rknn_server: 2.3.2 (1842325 build@2025-03-30T09:54:54)
D RKNNAPI:   DRV: rknnrt: 2.3.2 (429f97ae6b@2025-04-09T09:11:49)
D RKNNAPI: ==============================================
E RKNNAPI: rknn_init,  msg_load_ack fail, ack = 1(ACK_FAIL), expect 0(ACK_SUCC)!
E init_runtime: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2577, in rknn.api.rknn_base.RKNNBase.init_runtime
  File "rknn/api/rknn_runtime.py", line 427, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_MODEL_INVALID

W init_runtime: ===================== WARN(1) =====================
E rknn-toolkit2 version: 2.3.2
```

As i investigated the .rknn file's meta data, i found something interesting in it.

```
{
    "attrs": {
        "serving_default_input_1:0": {
            "idx": 0,
            "shape": [1, 3, 256, 256],
            "layout": "nchw",
            "layout_ori": "nhwc",
            "is_output": False,
            "range": [0, 1],
            "origin_dynamic": False,
            "dtype": "uint8",
            "mean": [0, 0, 0],
            "std": [1, 1, 1],
            "rgb2bgr": False
        },
        "StatefulPartitionedCall:0": {
            "is_output": True,
            "idx": 0,
            "shape": [1, 256, 256, 1],
            "dtype": "uint8",
            "layout": "nchw"
        }
    },
    "quant_tab": {
        "serving_default_input_1:0": {
            "name": "serving_default_input_1:0",
            "dtype": "int8",
            "qtype": "asym",
            "qmethod": "layer",
            "min": [0.0],
            "max": [1.0000000591389835],
            "scale": [0.003921568859368563],
            "zero_point": [-128],
            "narrow_range": False,
            "ori_min": [0.0],
            "ori_max": [1.0000000591389835]
        },
        "StatefulPartitionedCall:0": {
            "name": "StatefulPartitionedCall:0",
            "dtype": "int8",
            "qtype": "asym",
            "qmethod": "layer",
            "min": [0.0],
            "max": [10.890696309506893],
            "scale": [0.042708612978458405],
            "zero_point": [-128],
            "narrow_range": False,
            "ori_min": [0.0],
            "ori_max": [10.890696309506893]
        }
    },
    "dynamic_shapes": {}
}
```

The model takes input in NCHW format in proper RGB image with 3 Channels 256x256 size, and the output is a single channel grayscale image marked as NCHW instead of NHWC, so does it interpret the output layer having 256 channels?
it sounds like some version mismatch but all 3 modules are version 2.3.2.
```
Input:
shape      = [1, 3, 256, 256]
layout     = "nchw"
layout_ori = "nhwc"

Output:
shape  = [1, 256, 256, 1]
layout = "nchw"
```


i am very new to RockChip ecosystem, forgive me if i did any obvious thing wrong. please help :)
