### ISSUE TITLE
量化报错ValueError: Unsupport file -0.886949! 不做量化可以完成编译

### ISSUE THREAD

**Issue by cwr250** [airockchip/rknn-toolkit2#172]
量化报错ValueError: Unsupport file -0.886949! 不做量化可以完成编译。请问下是什么原因引起的呢？
![Screenshot 2024-10-10 162919](https://github.com/user-attachments/assets/0bc60026-935d-446c-99bf-6b4891c20724)

报错信息如下：
                        onnx::MatMul_10842                                 0.27        0.24        16.054, 14.695
                        model.encoders.48.self_attn.fsmn_block.weight      0.67        0.99        16.378
                        onnx::MatMul_11042                                 0.23        0.23        12.550
                        onnx::MatMul_11064                                 0.16        0.16        20.878, 20.629, 20.454, 20.446, 20.082
                        onnx::MatMul_11084                                 0.16        0.13        23.561, 23.303, 23.017, 22.497
                        onnx::MatMul_11104                                 0.16        0.13        24.980, 22.636
                        onnx::MatMul_11124                                 0.16        0.16        32.679, 32.335, 32.284, 32.228, 32.042
                        onnx::MatMul_11144                                 0.16        0.14        28.649, 27.235, 27.162, 26.938
                        onnx::MatMul_11164                                 0.16        0.14        27.306
                        onnx::MatMul_11184                                 0.16        0.13        15.910
                        onnx::MatMul_11424                                 0.16        0.14        -12.338
                        onnx::MatMul_11444                                 0.18        0.27        -14.326
D sparse_weight ...
E build: Unsupport file -0.886949!
W build: ===================== WARN(3) =====================
E rknn-toolkit2 version: 2.2.0
E build: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 1941, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/graph_optimizer.py", line 2304, in rknn.api.graph_optimizer.GraphOptimizer.sparse_weight
  File "rknn/api/sparse_weight.py", line 528, in rknn.api.sparse_weight.sparse_weight
  File "rknn/api/sparse_weight.py", line 75, in rknn.api.sparse_weight._range_input
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Unsupport file -0.886949!

I ===================== WARN(0) =====================
E rknn-toolkit2 version: 2.2.0
Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 1941, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/graph_optimizer.py", line 2304, in rknn.api.graph_optimizer.GraphOptimizer.sparse_weight
  File "rknn/api/sparse_weight.py", line 528, in rknn.api.sparse_weight.sparse_weight
  File "rknn/api/sparse_weight.py", line 75, in rknn.api.sparse_weight._range_input
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Unsupport file -0.886949!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/will/SenseVoice-ONNX/sensevoice/convert.py", line 31, in <module>
    ret = rknn.build(dataset=DATASET_PATH, do_quantization=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/will/miniforge3/envs/rknn/lib/python3.11/site-packages/rknn/api/rknn.py", line 192, in build
    return self.rknn_base.build(do_quantization=do_quantization, dataset=dataset, expand_batch_size=rknn_batch_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "rknn/api/rknn_log.py", line 314, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 1941, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/graph_optimizer.py", line 2304, in rknn.api.graph_optimizer.GraphOptimizer.sparse_weight
  File "rknn/api/sparse_weight.py", line 528, in rknn.api.sparse_weight.sparse_weight
  File "rknn/api/sparse_weight.py", line 75, in rknn.api.sparse_weight._range_input
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Unsupport file -0.886949!

**Comment by zen-xingle** [comment]
量化数据集里面，有名字异常的文件名

**Comment by cwr250** [comment]
> 量化数据集里面，有名字异常的文件名
确实是这个原因，找到问题所在了，多谢

**Comment by AllenY1987** [comment]
朋友能指导一下吗
