### ISSUE TITLE
rknn.accuracy_analysis连板推理报错

### ISSUE THREAD

**Issue by sangsasi** [airockchip/rknn-toolkit2#180]
使用rknn.load_rknn(RKNN_MODEL)
ret = rknn.init_runtime(target='rk3568',device_id='192.168.222.130:5555')可以正常推理。

但是用rknn.accuracy_analysis连板推理，就会报错，请问是什么原因？
rknn.accuracy_analysis代码如下：
ret = rknn.accuracy_analysis(inputs=['/data/rknn-toolkit2-gitee-image/rknn-toolkit2/examples/functions/accuracy_analysis/dog_224x224.jpg'], 
                                 output_dir='/data/rknn-toolkit2-gitee-image/rknn-toolkit2/examples/functions/accuracy_analysis/snapshot',
                                 target='rk3568')
错误日志如下：
--> Accuracy analysis
D adb path: /opt/conda/envs/rknn2.2.0/lib/python3.12/site-packages/rknn/3rdparty/platform-tools/adb/linux-x86_64/adb
adbd is already running as root
I target set by user is: rk3568
D adb path: /opt/conda/envs/rknn2.2.0/lib/python3.12/site-packages/rknn/3rdparty/platform-tools/adb/linux-x86_64/adb
I Get hardware info: target_platform = rk3568, os = Linux, aarch = aarch32
I Check RK3568 board npu runtime version
I Starting ntp or adb, target is RK3568
I Start adb...
I Connect to Device success!
I NPUTransfer(6771): Starting NPU Transfer Client, Transfer version 2.2.2 (12abf2a@2024-09-02T03:22:41)
D NPUTransfer(6771): Transfer spec = local:transfer_proxy
D NPUTransfer(6771): Transfer interface successfully opened, fd = 3
I NPUTransfer(6771): TransferBuffer: min aligned size: 1024
D RKNNAPI: ==============================================
D RKNNAPI: RKNN VERSION:
D RKNNAPI:   API: 2.2.0 (3e10681 build@2024-09-06T10:27:39)
D RKNNAPI:   DRV: rknn_server: 2.2.0 (3e10681 build@2024-09-06T10:26:40)
D RKNNAPI:   DRV: rknnrt: Unknown
D RKNNAPI: ==============================================
D RKNNAPI: Input tensors:
D RKNNAPI:   index=0, name=data, n_dims=4, dims=[1, 224, 224, 3], n_elems=150528, size=150528, w_stride = 0, size_with_stride = 0, fmt=NHWC, type=INT8, qnt_type=AFFINE, zp=-12, scale=0.017479
D RKNNAPI: Output tensors:
D RKNNAPI:   index=0, name=resnetv24_dense0_fwd, n_dims=2, dims=[1, 1000], n_elems=1000, size=1000, w_stride = 0, size_with_stride = 0, fmt=UNDEFINED, type=INT8, qnt_type=AFFINE, zp=-59, scale=0.074335
D NPUTransfer(6771): Transfer client closed, fd = 3
D adb path: /opt/conda/envs/rknn2.2.0/lib/python3.12/site-packages/rknn/3rdparty/platform-tools/adb/linux-x86_64/adb
adbd is already running as root
adb: error: failed to stat remote object '/data/dumps': No such file or directory
mv: cannot stat '/data/rknn-toolkit2-gitee-image/rknn-toolkit2/examples/functions/accuracy_analysis/snapshot/runtime/dumps': No such file or directory
E accuracy_analysis: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2829, in rknn.api.rknn_base.RKNNBase.accuracy_analysis
  File "rknn/api/rknn_base.py", line 2765, in rknn.api.rknn_base.RKNNBase._runtime_dump
FileNotFoundError: [Errno 2] No such file or directory: '/data/rknn-toolkit2-gitee-image/rknn-toolkit2/examples/functions/accuracy_analysis/snapshot/runtime/npy'

W accuracy_analysis: ===================== WARN(2) =====================
E rknn-toolkit2 version: 2.2.0
Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2829, in rknn.api.rknn_base.RKNNBase.accuracy_analysis
  File "rknn/api/rknn_base.py", line 2765, in rknn.api.rknn_base.RKNNBase._runtime_dump
FileNotFoundError: [Errno 2] No such file or directory: '/data/rknn-toolkit2-gitee-image/rknn-toolkit2/examples/functions/accuracy_analysis/snapshot/runtime/npy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/rknn-toolkit2-gitee-image/rknn-toolkit2/examples/functions/accuracy_analysis/test.py", line 106, in <module>
    ret = rknn.accuracy_analysis(inputs=['/data/rknn-toolkit2-gitee-image/rknn-toolkit2/examples/functions/accuracy_analysis/dog_224x224.jpg'], 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/rknn2.2.0/lib/python3.12/site-packages/rknn/api/rknn.py", line 275, in accuracy_analysis
    return self.rknn_base.accuracy_analysis(inputs, output_dir, target, device_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "rknn/api/rknn_log.py", line 314, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2829, in rknn.api.rknn_base.RKNNBase.accuracy_analysis
  File "rknn/api/rknn_base.py", line 2765, in rknn.api.rknn_base.RKNNBase._runtime_dump
FileNotFoundError: [Errno 2] No such file or directory: '/data/rknn-toolkit2-gitee-image/rknn-toolkit2/examples/functions/accuracy_analysis/snapshot/runtime/npy'

**Comment by yuyun2000** [comment]
看到报错没有'/data/rknn-toolkit2-gitee-image/rknn-toolkit2/examples/functions/accuracy_analysis/snapshot/runtime/npy' 这个目录，你能看到程序创建的这个目录吗？ 这个目录有权限可以被创建吗？ 自己创建一个对应的目录可以吗？ 这个目录一般来说是程序自己创建用来保存模型推理的中间张量的。
