### ISSUE TITLE
是不是rknn-toolkit2 在pypi上的包引用有什么问题，导致了无法通过requirements.txt进行更新，onnx的onnxoptimizer提示报错！！！

### ISSUE THREAD

**Issue by WilliamGrant** [airockchip/rknn-toolkit2#215]
我尝试将应用打包成ARM64架构的docker镜像，我的依赖如下
```
opencv-python-headless==4.10.0.84
https://download.pytorch.org/whl/cpu/torch-2.2.0-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl#sha256=a5f9772bb95efafd906de683104af2301ef18608d0c7f372ff1a5a61bf792b88
paddleocr==2.9.1
paddlepaddle==3.0.0b2
ultralytics==8.3.28
rknn-toolkit2==2.3.0
```
然后尝试使用pip进行安装打包成镜像，但是命令行提示:
```
#9 333.7 Collecting onnxoptimizer==0.2.7
#9 333.9   Downloading onnxoptimizer-0.2.7.tar.gz (16.8 MB)
#9 362.0     ERROR: Command errored out with exit status 1:
#9 362.0      command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2xj4qxe8/onnxoptimizer_51d59eadc6c04f65affd86accf69080f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2xj4qxe8/onnxoptimizer_51d59eadc6c04f65affd86accf69080f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dvb9c_7p
#9 362.0          cwd: /tmp/pip-install-2xj4qxe8/onnxoptimizer_51d59eadc6c04f65affd86accf69080f/
#9 362.0     Complete output (5 lines):
#9 362.0     Traceback (most recent call last):
#9 362.0       File "<string>", line 1, in <module>
#9 362.0       File "/tmp/pip-install-2xj4qxe8/onnxoptimizer_51d59eadc6c04f65affd86accf69080f/setup.py", line 75, in <module>
#9 362.0         assert CMAKE, 'Could not find "cmake" executable!'
#9 362.0     AssertionError: Could not find "cmake" executable!
#9 362.0     ----------------------------------------
#9 362.0 WARNING: Discarding https://files.pythonhosted.org/packages/a3/56/b7c3af61c87d565c4721c6d33b50fcc007c3545b1c5ffd118023ed342197/onnxoptimizer-0.2.7.tar.gz#sha256=a9f972b2b68ceb82b1f268042879f807fceb9ad76e38def2a39f102e62216d21 (from https://pypi.org/simple/onnxoptimizer/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#9 362.0 INFO: pip is looking at multiple versions of onnx to determine which version is compatible with other requirements. This could take a while.
#9 362.0 INFO: pip is looking at multiple versions of ultralytics to determine which version is compatible with other requirements. This could take a while.
#9 362.0 INFO: pip is looking at multiple versions of paddlepaddle to determine which version is compatible with other requirements. This could take a while.
#9 362.0 INFO: pip is looking at multiple versions of paddleocr to determine which version is compatible with other requirements. This could take a while.
#9 362.0 INFO: pip is looking at multiple versions of opencv-python-headless to determine which version is compatible with other requirements. This could take a while.
#9 362.0 INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
#9 362.0 INFO: pip is looking at multiple versions of torch to determine which version is compatible with other requirements. This could take a while.
#9 362.0 ERROR: Could not find a version that satisfies the requirement onnxoptimizer==0.2.7 (from rknn-toolkit2) (from versions: 0.2.7, 0.3.0, 0.3.1, 0.3.2, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.3.11, 0.3.12, 0.3.13)
#9 362.0 ERROR: No matching distribution found for onnxoptimizer==0.2.7
#9 364.4 WARNING: You are using pip version 21.1.3; however, version 24.3.1 is available.
#9 364.4 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
#9 ERROR: process "/dev/.buildkit_qemu_emulator /bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1

```
到这里就中断了整个镜像的打包，我想请问一下这个包里面究竟是什么内容，引用到到onnxoptimizer==0.2.7，但是却提醒无法匹配arm64,而且还是一个oldest版本。或者说有什么其他版本的rknn-tookit2能用的么？求指导。

**Comment by 1615070057** [comment]
ARM64版本不支持docker安装
