### ISSUE TITLE
rk3568跑示例报错

### ISSUE THREAD

**Issue by 2111905222** [airockchip/rknn-toolkit2#229]
D RKNN: [13:01:08.410] -----------------------------------------------------------------------+---------------------------------
D RKNN: [13:01:08.412] ----------------------------------------
D RKNN: [13:01:08.412] Total Internal Memory Size: 1764KB
D RKNN: [13:01:08.412] Total Weight Memory Size: 3606.25KB
D RKNN: [13:01:08.412] ----------------------------------------
D RKNN: [13:01:08.412] <<<<<<<< end: rknn::RKNNMemStatisticsPass
I rknn building done.
done
--> Accuracy analysis
D adb path: /usr/bin/adb
adbd is already running as root
I target set by user is: rk3568
D adb path: /usr/bin/adb
I Get hardware info: target_platform = rk3568, os = Android, aarch = aarch64
I Check RK3568 board npu runtime version
I Starting ntp or adb, target is RK3568
I Start adb...
I Connect to Device success!
I NPUTransfer(170): Starting NPU Transfer Client, Transfer version 2.2.2 (12abf2a@2024-09-02T03:22:41)
D NPUTransfer(170): Transfer spec = local:transfer_proxy
D NPUTransfer(170): Transfer interface successfully opened, fd = 3
I NPUTransfer(170): TransferBuffer: min aligned size: 1024
E RKNNAPI: rknn_server version is too old, please update rknn_server to at least 2.3.0

E accuracy_analysis: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2483, in rknn.api.rknn_base.RKNNBase.init_runtime
  File "rknn/api/rknn_runtime.py", line 427, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_FAIL

W accuracy_analysis: ===================== WARN(3) =====================
E rknn-toolkit2 version: 2.3.0
E accuracy_analysis: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2483, in rknn.api.rknn_base.RKNNBase.init_runtime
  File "rknn/api/rknn_runtime.py", line 427, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_FAIL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2881, in rknn.api.rknn_base.RKNNBase.accuracy_analysis
  File "rknn/api/rknn_base.py", line 2772, in rknn.api.rknn_base.RKNNBase._runtime_dump
  File "rknn/api/rknn_log.py", line 349, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2483, in rknn.api.rknn_base.RKNNBase.init_runtime
  File "rknn/api/rknn_runtime.py", line 427, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_FAIL

I ===================== WARN(0) =====================
E rknn-toolkit2 version: 2.3.0
Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2483, in rknn.api.rknn_base.RKNNBase.init_runtime
  File "rknn/api/rknn_runtime.py", line 427, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_FAIL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2881, in rknn.api.rknn_base.RKNNBase.accuracy_analysis
  File "rknn/api/rknn_base.py", line 2772, in rknn.api.rknn_base.RKNNBase._runtime_dump
  File "rknn/api/rknn_log.py", line 349, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2483, in rknn.api.rknn_base.RKNNBase.init_runtime
  File "rknn/api/rknn_runtime.py", line 427, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_FAIL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 52, in <module>
    ret = rknn.accuracy_analysis(inputs=['./dog_224x224.jpg'], output_dir='./snapshot', target='rk3568')
  File "/usr/local/lib/python3.8/dist-packages/rknn/api/rknn.py", line 275, in accuracy_analysis
    return self.rknn_base.accuracy_analysis(inputs, output_dir, target, device_id)
  File "rknn/api/rknn_log.py", line 349, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2483, in rknn.api.rknn_base.RKNNBase.init_runtime
  File "rknn/api/rknn_runtime.py", line 427, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_FAIL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2881, in rknn.api.rknn_base.RKNNBase.accuracy_analysis
  File "rknn/api/rknn_base.py", line 2772, in rknn.api.rknn_base.RKNNBase._runtime_dump
  File "rknn/api/rknn_log.py", line 349, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2483, in rknn.api.rknn_base.RKNNBase.init_runtime
  File "rknn/api/rknn_runtime.py", line 427, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_FAIL

**Comment by yuyun2000** [comment]
E RKNNAPI: rknn_server version is too old, please update rknn_server to at least 2.3.0
