### ISSUE TITLE
tts中vits系列的Melo模型--将onnx转换rknn报错

### ISSUE THREAD

**Issue by crayonxin1** [airockchip/rknn-toolkit2#230]
想使用rk3588的npu对melo加速，在将onnx转换为rknn时遇到了一些问题。
通过netron查看了melo的onnx模型的输入tensor: int64[N,L]和输出tensor: int64[N,L]是动态的
1、添加了dynamic_input，转换时报错
File "rknn/api/rknn_log.py". line 95. in rknn.api.rknn_log.RKNNLog.e
ValueError: The shape of '/sdp/flows.7/Transpose 2_output,0' is (0，3)，it is abnormal!
2、将onnx的输入修改为固定值，再在转换为rknn的过程中报错
Traceback (most recent call last):
  File "/userdata/Downloads/MeloTTS-main/test_rknn.py", line 21, in <module>
    ret = rknn.build(do_quantization=False)
  File "/home/teamhd/miniconda3/envs/rknn-toolkit/lib/python3.10/site-packages/rknn/api/rknn.py", line 192, in build
    return self.rknn_base.build(do_quantization=do_quantization, dataset=dataset, expand_batch_size=rknn_batch_size)
  File "rknn/api/rknn_log.py", line 349, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 1945, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/graph_optimizer.py", line 893, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
  File "rknn/api/graph_optimizer.py", line 366, in rknn.api.graph_optimizer._dynamic_check
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: The input 0 of NonZero('/sdp/flows.7/NonZero') need to be constant! It will cause the graph to be a dynamic graph!
                  Remove NonZero('/sdp/flows.7/NonZero') manually and try again!

想问一下该如何解决？或者可以直接用pytorch源码进行npu加速吗，具体应该怎么做呢？

**Comment by Chinneil** [comment]
我现在也遇到这个问题，请问，你这个问题解决了吗
@crayonxin1

**Comment by zzhdbw** [comment]
有解决办法了吗，我也遇到了这个问题。

**Comment by bututou777** [comment]
将unconstrained_rational_quadratic_spline函数里面类似与xxx[mask]=yyy[mask]的赋值方式全改为torch.add和*的方式实现这样就可以完全去掉了NonZero算子

**Comment by zzhdbw** [comment]
感谢！
