### ISSUE TITLE
"import pytorch" gives error on rk3588 board.

### ISSUE THREAD

**Issue by ZihengQiu** [airockchip/rknn-toolkit2#28]
# description
Running python in rk3588 gives error:

> Traceback (most recent call last):
  File "yolov8_lite_video.py", line 8, in <module>
    import torch
  File "/home/khadas/miniconda3/envs/npu-env-1.4/lib/python3.8/site-packages/torch/__init__.py", line 1829, in <module>
    from torch import export as export
  File "/home/khadas/miniconda3/envs/npu-env-1.4/lib/python3.8/site-packages/torch/export/__init__.py", line 29, in <module>
    from torch.fx.passes.infra.pass_base import PassResult
  File "/home/khadas/miniconda3/envs/npu-env-1.4/lib/python3.8/site-packages/torch/fx/passes/__init__.py", line 3, in <module>
    from . import net_min_base
  File "/home/khadas/miniconda3/envs/npu-env-1.4/lib/python3.8/site-packages/torch/fx/passes/net_min_base.py", line 11, in <module>
    from .split_utils import split_by_tags
  File "/home/khadas/miniconda3/envs/npu-env-1.4/lib/python3.8/site-packages/torch/fx/passes/split_utils.py", line 8, in <module>
    from torch.fx.passes.utils import HolderModule, lift_subgraph_as_module
  File "/home/khadas/miniconda3/envs/npu-env-1.4/lib/python3.8/site-packages/torch/fx/passes/utils/__init__.py", line 1, in <module>
    from .common import lift_subgraph_as_module, HolderModule, compare_graphs
  File "/home/khadas/miniconda3/envs/npu-env-1.4/lib/python3.8/site-packages/torch/fx/passes/utils/common.py", line 7, in <module>
    from torch.fx.passes.utils.matcher_utils import SubgraphMatcher
  File "/home/khadas/miniconda3/envs/npu-env-1.4/lib/python3.8/site-packages/torch/fx/passes/utils/matcher_utils.py", line 31, in <module>
    logger = _init_logger()
  File "/home/khadas/miniconda3/envs/npu-env-1.4/lib/python3.8/site-packages/torch/fx/passes/utils/matcher_utils.py", line 21, in _init_logger
    logger.setLevel(level)
  File "/home/khadas/miniconda3/envs/npu-env-1.4/lib/python3.8/logging/__init__.py", line 1421, in setLevel
    self.level = _checkLevel(level)
  File "/home/khadas/miniconda3/envs/npu-env-1.4/lib/python3.8/logging/__init__.py", line 198, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'WARNING'

The first line of the python code is as follows:
``` import os
import cv2
import sys
import argparse
import numpy as np
import platform
from rknnlite.api import RKNNLite
import torch
```
I have tried to search for the error but still have no idea what's the potential solution. I try to downgrade python from version 3.9 to 3.8, but the error still occurs.
# environment
`conda list` gives following result:
```
# Name                    Version                   Build  Channel                                                                                            
_libgcc_mutex             0.1                        main    defaults                                                                                         
_openmp_mutex             5.1                      51_gnu    defaults                                                                                         
blas                      1.0                    openblas    defaults                                                                                         
brotli-python             1.0.9            py38h419075a_7    defaults                                                                                         
bzip2                     1.0.8                h998d150_5    defaults                                                                                         
c-ares                    1.19.1               h998d150_0    defaults                                                                                         
ca-certificates           2024.3.11            hd43f75c_0    defaults                                                                                         
cairo                     1.16.0               h537eab0_5    defaults                                                                                         
certifi                   2024.2.2         py38hd43f75c_0    defaults                                                                                         
cffi                      1.16.0           py38h998d150_0    defaults                                                                                         
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults                                                                                         
cyrus-sasl                2.1.28               h647bc0d_1    defaults                                                                                         
dbus                      1.13.18              h821dc26_0    defaults                                                                                         
eigen                     3.4.0                hb8fdbf2_0    defaults                                                                                         
expat                     2.5.0                h419075a_0    defaults                                                                                         
ffmpeg                    4.2.2                hdfaaa67_0    defaults                                                                                         
filelock                  3.13.4                   pypi_0    pypi                                                                                             
fontconfig                2.14.1               h652894d_2    defaults 
freeglut                  3.0.0                h22f4aa5_5    defaults                                                                                 
freetype                  2.12.1               h6df46f4_0    defaults                                                                                         
fsspec                    2024.3.1                 pypi_0    pypi                                                                                             
future                    0.18.3           py38hd43f75c_0    defaults                                                                                         
gettext                   0.21.0               h0cce8dc_1    defaults                                                                                         
giflib                    5.2.1                h998d150_3    defaults                                                                                         
glib                      2.78.4               h419075a_0    defaults                                                                                         
glib-tools                2.78.4               h419075a_0    defaults                                                                                         
gmp                       6.2.1                h22f4aa5_3    defaults                                                                                         
gnutls                    3.6.15               hc6589d6_0    defaults                                                                                         
graphite2                 1.3.14               h22f4aa5_1    defaults                                                                                         
gst-plugins-base          1.22.3               h94b7715_0    defaults                                                                                         
gst-plugins-good          1.22.3               h419075a_0    defaults                                                                                         
gstreamer                 1.22.3               h998d150_0    defaults                                                                                         
harfbuzz                  2.8.0                h905054b_0    defaults                                                                                         
hdf5                      1.10.6               h8b20701_1    defaults                                                                                         
icu                       68.1                 h22f4aa5_0    defaults                                                                                         
idna                      3.4              py38hd43f75c_0    defaults                                                                                         
jasper                    2.0.14               hf85ac85_2    defaults                                                                                         
jinja2                    3.1.3                    pypi_0    pypi                                                                                             
joblib                    1.2.0            py38hd43f75c_0    defaults                                                                                         
jpeg                      9e                   h998d150_1    defaults                                                                                         
krb5                      1.20.1               h2e2fba8_1    defaults                                                                                         
lame                      3.100                hfd63f10_0    defaults                                                                                         
ld_impl_linux-aarch64     2.38                 h8131f2d_1    defaults                                                                                         
lerc                      3.0                  h22f4aa5_0    defaults                                                                                         
libclang                  14.0.6          default_hd3a980f_1    defaults                                                                                      
libclang13                14.0.6          default_h5e70c7c_1    defaults                                                                                      
libcups                   2.4.2                hb788212_1    defaults                                                                                         
libcurl                   8.5.0                hfa2bbb0_0    defaults                                                                                         
libdeflate                1.17                 h998d150_1    defaults                                                                                         
libedit                   3.1.20230828         h998d150_0    defaults                                                                                         
libev                     4.33                 hfd63f10_1    defaults                                                                                         
libevent                  2.1.12               h6ac735f_1    defaults                                                                                         
libffi                    3.4.4                h419075a_0    defaults                                                                                         
libgcc-ng                 11.2.0               h1234567_1    defaults                                                                                         
libgfortran-ng            11.2.0               h6e398d7_1    defaults                                                                                         
libgfortran5              11.2.0               h1234567_1    defaults                                                                                         
libglib                   2.78.4               hd439bcf_0    defaults                                                                                         
libglu                    9.0.0                h22f4aa5_1    defaults
libgomp                   11.2.0               h1234567_1    defaults                                                                                 [40/281]
libiconv                  1.16                 h2f4d8fa_2    defaults                                                                                         
libidn2                   2.3.4                h998d150_0    defaults                                                                                         
libllvm14                 14.0.6               hb8fdbf2_3    defaults                                                                                         
libnghttp2                1.57.0               hb788212_0    defaults                                                                                         
libogg                    1.3.5                h2f4d8fa_1    defaults                                                                                         
libopenblas               0.3.21               hc2e42e2_0    defaults                                                                                         
libopencv                 4.5.2            py38h3114f89_0    defaults                                                                                         
libopus                   1.3.1                h2f4d8fa_0    defaults                                                                                         
libpng                    1.6.39               h998d150_0    defaults                                                                                         
libpq                     12.17                h6ac735f_0    defaults                                                                                         
libprotobuf               3.14.0               h549d06d_0    defaults                                                                                         
libssh2                   1.10.0               h6ac735f_2    defaults                                                                                         
libstdcxx-ng              11.2.0               h1234567_1    defaults                                                                                         
libtasn1                  4.19.0               h998d150_0    defaults                                                                                         
libtiff                   4.5.1                h419075a_0    defaults                                                                                         
libunistring              0.9.10               h2f4d8fa_0    defaults                                                                                         
libuuid                   1.41.5               h998d150_0    defaults                                                                                         
libvorbis                 1.3.7                hfd63f10_0    defaults                                                                                         
libvpx                    1.8.2                h7c1a80f_0    defaults                                                                                         
libwebp                   1.3.2                he1bfee4_0    defaults                                                                                         
libwebp-base              1.3.2                h998d150_0    defaults                                                                                         
libxcb                    1.15                 h2f4d8fa_0    defaults                                                                                         
libxkbcommon              1.0.1                h998d150_1    defaults                                                                                         
libxml2                   2.10.4               hd6958ba_0    defaults                                                                                         
libxslt                   1.1.37               h4d22567_0    defaults                                                                                         
lz4-c                     1.9.4                h419075a_0    defaults                                                                                         
markupsafe                2.1.5                    pypi_0    pypi                                                                                             
mpg123                    1.30.0            h419075a_1000    defaults                                                                                         
mpmath                    1.3.0                    pypi_0    pypi                                                                                             
mysql                     5.7.24               h3140d82_2    defaults                                                                                         
ncurses                   6.4                  h419075a_0    defaults                                                                                         
nettle                    3.7.3                h82288b7_1    defaults                                                                                         
networkx                  3.1                      pypi_0    pypi                                                                                             
ninja                     1.10.2               hd43f75c_5    defaults                                                                                         
ninja-base                1.10.2               h59a28a9_5    defaults                                                                                         
nspr                      4.35                 h419075a_0    defaults                                                                                         
nss                       3.89.1               h419075a_0    defaults                                                                                         
numpy                     1.24.3           py38h8708280_0    defaults                                                                                         
numpy-base                1.24.3           py38h4a83355_0    defaults 
opencv                    4.5.2            py38hd43f75c_0    defaults
openh264                  1.8.0                h22f4aa5_0    defaults
openssl                   3.0.13               h2f4d8fa_0    defaults
packaging                 23.2             py38hd43f75c_0    defaults
pcre2                     10.42                hcfaa891_0    defaults
pip                       23.3.1           py38hd43f75c_0    defaults
pixman                    0.40.0               h2f4d8fa_1    defaults
platformdirs              3.10.0           py38hd43f75c_0    defaults
pooch                     1.7.0            py38hd43f75c_0    defaults
psutil                    5.9.8                    pypi_0    pypi
py-opencv                 4.5.2            py38h7100cfe_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pysocks                   1.7.1            py38hd43f75c_0    defaults
python                    3.8.19               h4bb2201_0    defaults
pyyaml                    6.0.1            py38h998d150_0    defaults
readline                  8.2                  h998d150_0    defaults
requests                  2.31.0           py38hd43f75c_1    defaults
rknn-toolkit-lite2        2.0.0b0                  pypi_0    pypi
ruamel-yaml               0.18.6                   pypi_0    pypi
ruamel-yaml-clib          0.2.8                    pypi_0    pypi
scikit-learn              1.3.0            py38hfb1e5ee_1    defaults
scipy                     1.10.1           py38h7caaa05_1    defaults
setuptools                68.2.2           py38hd43f75c_0    defaults
sqlite                    3.41.2               h998d150_0    defaults
sympy                     1.12                     pypi_0    pypi
threadpoolctl             2.2.0              pyh0d69192_0    defaults
tk                        8.6.12               h241ca14_0    defaults
torch                     2.2.2                    pypi_0    pypi
typing-extensions         4.9.0            py38hd43f75c_1    defaults
typing_extensions         4.9.0            py38hd43f75c_1    defaults
tzdata                    2024a                h04d1e81_0    defaults
urllib3                   2.1.0            py38hd43f75c_1    defaults
wheel                     0.41.2           py38hd43f75c_0    defaults
x264                      1!152.20180806       h2f4d8fa_0    defaults
xz                        5.4.6                h998d150_0    defaults
yaml                      0.2.5                hfd63f10_0    defaults
zlib                      1.2.13               h998d150_0    defaults
zstd                      1.5.5                h6a09583_0    defaults
```
and command
`strings /usr/lib/librknnrt.so | grep -i "librknnrt"`
 gives
```
librknnrt.so
librknnrt version: 2.0.0b0 (35a6907d79@2024-03-24T10:31:14)
, but current librknnrt.so is support model version <= 
Unsupport GPU op: %s in this librknnrt.so, please try to register custom op by calling rknn_register_custom_ops or %s
Unsupport CPU op: %s in this librknnrt.so, please try to register custom op by callingrknn_register_custom_ops or %s
Unsupport GPU op: %s in this librknnrt.so, %s
```

**Comment by ZihengQiu** [comment]
If I run the python code **in ros as a node**, the **same error** will caused by rospy.init("_node_name_").
Interestingly, the error will disappear if I comment 
`from rknnlite.api import RKNNLite`
, and shows:
`NameError: name api is not found`, even with torch imported.
So, from my perspective of view, the error is related to rknnlite.api rather than torch.

**Comment by gaoxumustwin** [comment]
hi brother,I also encountered this problem, and my solution was to change the torch version to 1.13, which was successfully resolved in the end

**Comment by gaoxumustwin** [comment]
https://blog.csdn.net/gaoxukkk888/article/details/139806562?spm=1001.2014.3001.5501

**Comment by knifecutter** [comment]
应该是logging 库存在冲突，可以将from rknnlite.api import RKNNLite 放置到 RKNNLite 初始化前。

**Comment by Lu-tju** [comment]
> 应该是logging 库存在冲突，可以将from rknnlite.api import RKNNLite 放置到 RKNNLite 初始化前。

感谢！有效！我也是在ROS时遇到的此错误

**Comment by AIWintermuteAI** [comment]
Same error when trying to use rknn2-lite with Gradio:
```
(venv) luckfox@luckfox:~/rknn-llm/examples/rkllm_server_demo/rkllm_server$ python3 gradio_server.py --rkllm_model_path ~/models/Qwen2-VL-2B-Instruct.rkllm --target_platform rk3576 --mmproj_model_path ~/models/qwen2_vl_2b_vision_rk3576.rknn 
/home/luckfox/rknn-llm/examples/rkllm_server_demo/rkllm_server/gradio_server.py:385: UserWarning: You have not specified a value for the `type` parameter. Defaulting to the 'tuples' format for chatbot messages, but this is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style dictionaries with 'role' and 'content' keys.
  rkllmServer = gr.Chatbot(height=600)
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/config.py", line 616, in configure
    self.configure_logger(name, loggers[name])
  File "/usr/lib/python3.11/logging/config.py", line 797, in configure_logger
    self.common_logger_config(logger, config, incremental)
  File "/usr/lib/python3.11/logging/config.py", line 782, in common_logger_config
    logger.setLevel(logging._checkLevel(level))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 207, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'INFO'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/luckfox/rknn-llm/examples/rkllm_server_demo/rkllm_server/gradio_server.py", line 409, in <module>
    chatRKLLM.launch()
  File "/home/luckfox/venv/lib/python3.11/site-packages/gradio/blocks.py", line 2638, in launch
    ) = http_server.start_server(
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luckfox/venv/lib/python3.11/site-packages/gradio/http_server.py", line 130, in start_server
    config = uvicorn.Config(
             ^^^^^^^^^^^^^^^
  File "/home/luckfox/venv/lib/python3.11/site-packages/uvicorn/config.py", line 274, in __init__
    self.configure_logging()
  File "/home/luckfox/venv/lib/python3.11/site-packages/uvicorn/config.py", line 366, in configure_logging
    logging.config.dictConfig(self.log_config)
  File "/usr/lib/python3.11/logging/config.py", line 812, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.11/logging/config.py", line 618, in configure
    raise ValueError('Unable to configure logger '
ValueError: Unable to configure logger 'uvicorn'
```
Moving the rknn import to the later point in flow (before the inference as opposed to program init) helped, but does seem more like a hack.
@ZihengQiu thoughts on this one? Affected quite a few users.

**Comment by JiangLiiiii** [comment]
> hi brother,I also encountered this problem, and my solution was to change the torch version to 1.13, which was successfully resolved in the end

thanks bro, it works!
