### ISSUE TITLE
转模型过程中出现算子错误

### ISSUE THREAD

**Issue by YHaooo-4508** [airockchip/rknn-toolkit2#43]
我尝试用最新的rknn-toolkit2将自己的onnx模型转为rk模型，是遇到一个错误，并且我无法通过这个报错追溯到源码的位置，具体报错日志如下

--> Building model
Build model failed!
E build: Catch exception when building RKNN model!
E build: Traceback (most recent call last):
E build:   File "rknn/api/rknn_base.py", line 1979, in rknn.api.rknn_base.RKNNBase.build
E build:   File "rknn/api/graph_optimizer.py", line 1365, in rknn.api.graph_optimizer.GraphOptimizer.correct_ops
E build: TypeError: '>' not supported between instances of 'numpy.ndarray' and 'str'

**Comment by scarlet-tt-tt** [comment]
您好，我遇到了同样的问题，请问您后续解决了吗？

**Comment by YHaooo-4508** [comment]
解决不了，rknn你在github qq群等地方提问题是不会有任何反馈的，只有老老实实等rknn更新，或者自己修改模型穷举来一步一步去试问题到底出现在哪个算子上

**Comment by scarlet-tt-tt** [comment]
> 解决不了，rknn你在github qq群等地方提问题是不会有任何反馈的，只有老老实实等rknn更新，或者自己修改模型穷举来一步一步去试问题到底出现在哪个算子上

天、、、非常谢谢你的回复，我这个模型转一周了各种出问题，感觉得放弃了
