### ISSUE TITLE
RKNN-toolkit2 install fail

### ISSUE THREAD

**Issue by PJ5168** [airockchip/rknn-toolkit2#56]
OS : clean WSL2/Ubuntu 22.04 LTS +  conda + python3.10
Follow the instruction in the document, installed following two without error.
1. pip install -r packages/rknn_toolkit2-2.0.0b0+9bab5682-cp310-cp310-linux_x86_64.whl
2. pip install packages/rknn_toolkit2-2.0.0b0+9bab5682-cp310-cp310-linux_x86_64.whl

error message : 
Python 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rknn.api import RKNN
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pj/miniconda3/envs/RKNN/lib/python3.10/site-packages/rknn/api/__init__.py", line 1, in <module>
    from rknn.api.rknn import RKNN
  File "/home/pj/miniconda3/envs/RKNN/lib/python3.10/site-packages/rknn/api/rknn.py", line 7, in <module>
    from .rknn_base import RKNNBase
  File "rknn/api/rknn_base.py", line 26, in init rknn.api.rknn_base
  File "rknn/api/codegen.py", line 4, in init rknn.api.codegen
  File "/home/pj/miniconda3/envs/RKNN/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/pj/miniconda3/envs/RKNN/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/pj/miniconda3/envs/RKNN/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

solution : 
pip install opencv-python-headless

**Comment by yuyun2000** [comment]
it is vert good 你可以把issue关了其实

**Comment by zpcore** [comment]
Try:
```
sudo apt-get update && sudo apt-get install libgl1
```
