### ISSUE TITLE
Trouble with install req.txt and whl file for my RK3588

### ISSUE THREAD

**Issue by Artem-N** [airockchip/rknn-toolkit2#8]
Hello, may i ask about help - when i try install lib for working in future with yolov7 on step install requirements - i have trouble and don`t know what to do.  I try diff version of python, updated diff lib etc. 
i have ubuntu 20.04, python 64 (not 32), rk 3588 aarch64 

Building wheel for onnxoptimizer (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for onnxoptimizer (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [82 lines of output]
      fatal: not a git repository (or any parent up to mount point /)
      Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
      /tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/dist.py:476: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'license-file' will not be supported in future
              versions. Please use the underscore name 'license_file' instead.
      
              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      running bdist_wheel
      running build
      running build_py
      running create_version
      running cmake_build
      CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
        CMake 3.22 or higher is required.  You are running version 3.16.3
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/home/orangepi/test_rknn/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/orangepi/test_rknn/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/orangepi/test_rknn/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 410, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 320, in <module>
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-0zivm9u6/normal/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 216, in run
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-0zivm9u6/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 202, in run
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/cmake', '-DPython_INCLUDE_DIR=/usr/include/python3.10', '-DPython_EXECUTABLE=/home/orangepi/test_rknn/bin/python3.10', '-DBUILD_ONNX_PYTHON=ON', '-DONNX_USE_LITE_PROTO=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-310-aarch64-linux-gnu.so', '-DONNX_OPT_USE_SYSTEM_PROTOBUF=OFF', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-eahlw5iq/onnxoptimizer_3ffb076dd8c4437882f687ded2028415']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onnxoptimizer
  Building wheel for psutil (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for psutil (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-310
      creating build/lib.linux-aarch64-cpython-310/psutil
      copying psutil/_pswindows.py -> build/lib.linux-aarch64-cpython-310/psutil
      copying psutil/_pssunos.py -> build/lib.linux-aarch64-cpython-310/psutil
      copying psutil/_psposix.py -> build/lib.linux-aarch64-cpython-310/psutil
      copying psutil/_psosx.py -> build/lib.linux-aarch64-cpython-310/psutil
      copying psutil/_pslinux.py -> build/lib.linux-aarch64-cpython-310/psutil
      copying psutil/_psbsd.py -> build/lib.linux-aarch64-cpython-310/psutil
      copying psutil/_psaix.py -> build/lib.linux-aarch64-cpython-310/psutil
      copying psutil/_compat.py -> build/lib.linux-aarch64-cpython-310/psutil
      copying psutil/_common.py -> build/lib.linux-aarch64-cpython-310/psutil
      copying psutil/__init__.py -> build/lib.linux-aarch64-cpython-310/psutil
      creating build/lib.linux-aarch64-cpython-310/psutil/tests
      copying psutil/tests/test_windows.py -> build/lib.linux-aarch64-cpython-310/psutil/tests
      copying psutil/tests/test_unicode.py -> build/lib.linux-aarch64-cpython-310/psutil/tests
      copying psutil/tests/test_testutils.py -> build/lib.linux-aarch64-cpython-310/psutil/tests
      copying psutil/tests/test_system.py -> build/lib.linux-aarch64-cpython-310/psutil/tests
      copying psutil/tests/test_sunos.py -> build/lib.linux-aarch64-cpython-310/psutil/tests
      copying psutil/tests/test_process_all.py -> build/lib.linux-aarch64-cpython-310/psutil/tests
      copying psutil/tests/test_process.py -> build/lib.linux-aarch64-cpython-310/psutil/tests
      copying psutil/tests/test_posix.py -> build/lib.linux-aarch64-cpython-310/psutil/tests
      copying psutil/tests/test_osx.py -> build/lib.linux-aarch64-cpython-310/psutil/tests
      copying psutil/tests/test_misc.py -> build/lib.linux-aarch64-cpython-310/psutil/tests
      copying psutil/tests/test_memleaks.py -> build/lib.linux-aarch64-cpython-310/psutil/tests
      copying psutil/tests/test_linux.py -> build/lib.linux-aarch64-cpython-310/psutil/tests
      copying psutil/tests/test_contracts.py -> build/lib.linux-aarch64-cpython-310/psutil/tests
      copying psutil/tests/test_connections.py -> build/lib.linux-aarch64-cpython-310/psutil/tests
      copying psutil/tests/test_bsd.py -> build/lib.linux-aarch64-cpython-310/psutil/tests
      copying psutil/tests/test_aix.py -> build/lib.linux-aarch64-cpython-310/psutil/tests
      copying psutil/tests/runner.py -> build/lib.linux-aarch64-cpython-310/psutil/tests
      copying psutil/tests/__main__.py -> build/lib.linux-aarch64-cpython-310/psutil/tests
      copying psutil/tests/__init__.py -> build/lib.linux-aarch64-cpython-310/psutil/tests
      running build_ext
      building 'psutil._psutil_linux' extension
      creating build/temp.linux-aarch64-cpython-310
      creating build/temp.linux-aarch64-cpython-310/psutil
      creating build/temp.linux-aarch64-cpython-310/psutil/arch
      creating build/temp.linux-aarch64-cpython-310/psutil/arch/linux
      aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=598 -DPy_LIMITED_API=0x03060000 -DPSUTIL_LINUX=1 -I/home/orangepi/test_rknn/include -I/usr/include/python3.10 -c psutil/_psutil_common.c -o build/temp.linux-aarch64-cpython-310/psutil/_psutil_common.o
      psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
          9 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      psutil could not be installed from sources. Perhaps Python header files are not installed. Try running:
        sudo apt-get install gcc python3-dev
      error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psutil
Failed to build onnxoptimizer psutil
ERROR: Could not build wheels for onnxoptimizer, psutil, which is required to install pyproject.toml-based projects

**Comment by Artem-N** [comment]
and when try install .whl - ERROR: rknn_toolkit2-1.6.0+81f21f4d-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.

**Comment by fronos** [comment]
Try to upgrade CMake. In your previous comment exist line that says that you have 3.16 but required cmake 3.22 or higher

**Comment by fronos** [comment]
Use lite version for rockchip board. Full version library is need for model conversion.

**Comment by Artem-N** [comment]
> Try to upgrade CMake. In your previous comment exist line that says that you have 3.16 but required cmake 3.22 or higher

yep, but its don`t help, i`m trying to update cmake, onnxoptimizer , and now see you answer and try install lite version ) thanks :) go for trying
