### ISSUE TITLE
是否支持vits等语音模型

### ISSUE THREAD

**Issue by pengpengtao** [airockchip/rknn-toolkit2#84]
--> Config model
done
--> Loading model
I It is recommended onnx opset 19, but your onnx model opset is 13!
I Model converted from pytorch, 'opset_version' should be set 19 in torch.onnx.export for successful convert!
I Loading : 100%|███████████████████████████████████████████| 1892/1892 [00:00<00:00, 293803.15it/s]
E load_onnx: The input shape ['N', 'T'] of 'tokens' is not support!
                              Please set the 'inputs' / 'input_size_list' parameters of 'rknn.load_onnx', or set the 'dyanmic_input' parameter of 'rknn.config' to fix the input shape!
I ===================== WARN(0) =====================
E rknn-toolkit2 version: 2.0.0b0+9bab5682
E load_onnx: Catch exception when loading onnx model: /mnt/f/7_8/vits/python-api-examples/vits-icefall-zh-aishell3/model.onnx!
E load_onnx: Traceback (most recent call last):
E load_onnx:   File "rknn/api/rknn_base.py", line 1546, in rknn.api.rknn_base.RKNNBase.load_onnx
E load_onnx:   File "rknn/api/rknn_base.py", line 764, in rknn.api.rknn_base.RKNNBase._create_ir_and_inputs_meta
E load_onnx:   File "rknn/api/rknn_log.py", line 92, in rknn.api.rknn_log.RKNNLog.e
E load_onnx: ValueError: The input shape ['N', 'T'] of 'tokens' is not support!
E load_onnx:                               Please set the 'inputs' / 'input_size_list' parameters of 'rknn.load_onnx', or set the 'dyanmic_input' parameter of 'rknn.config' to fix the input shape!

**Comment by yuyun2000** [comment]
得设置输入长度呢

**Comment by pengpengtao** [comment]
> 得设置输入长度呢

有参考例子吗

**Comment by yuyun2000** [comment]
你这个模型是动态的输入，你要么设置几个动态输入，要么把onnx的shape固定一下

**Comment by pengpengtao** [comment]
我设置动态输入好像不管用，如果固定onnx的shape，那么文字长度也固定，感觉不合适

**Comment by yuyun2000** [comment]
是的，所以他是不太合适转rknn的

**Comment by pengpengtao** [comment]
> 是的，所以他是不太合适转rknn的

我好像已经解决了，支持任意长度的文字输出音频

**Comment by yuyun2000** [comment]
这么强？莫非是用了pad？还是mask？

**Comment by pengpengtao** [comment]
用了pad，比onnx快了4倍

**Comment by yuyun2000** [comment]
最长能推理多长的文本？ 文本过短的时候是不是要浪费后面那么多token了

**Comment by pengpengtao** [comment]
30s是没有问题，具体多长没测试过，只要模型能支持的最大长度应该都能达到。如果文本过短确实会浪费token，但是浪费比较少，我测试了一个字的token和音频长度，然后设置的阈值是74，如果切段z_p的长度小于74才padding，所以并不会浪费很多。阈值也可以设置55，但是我听起来有点不自然。可能需要根据不同的模型，设置不同的阈值，我尝试了0-256的阈值

**Comment by yuyun2000** [comment]
太强了

**Comment by wbjnpu** [comment]
最好的解决方案是 后置编码器和声码器按chunk导出，毕竟前端不费资源，后端可以流式生成

**Comment by yuyun2000** [comment]
> 最好的解决方案是 后置编码器和声码器按chunk导出，毕竟前端不费资源，后端可以流式生成

你说得对

**Comment by wbjnpu** [comment]
> > 最好的解决方案是 后置编码器和声码器按chunk导出，毕竟前端不费资源，后端可以流式生成
> 
> 你说得对

我确实是这样做的，这样在npu上可以跑比较大的模型

**Comment by wbjnpu** [comment]
> 30s是没有问题，具体多长没测试过，只要模型能支持的最大长度应该都能达到。如果文本过短确实会浪费token，但是浪费比较少，我测试了一个字的token和音频长度，然后设置的阈值是74，如果切段z_p的长度小于74才padding，所以并不会浪费很多。阈值也可以设置55，但是我听起来有点不自然。可能需要根据不同的模型，设置不同的阈值，我尝试了0-256的阈值

请问你导出是int8量化么，int8量化后的模型有很明显的噪声你是怎么解决的

**Comment by yuyun2000** [comment]
> > 30s是没有问题，具体多长没测试过，只要模型能支持的最大长度应该都能达到。如果文本过短确实会浪费token，但是浪费比较少，我测试了一个字的token和音频长度，然后设置的阈值是74，如果切段z_p的长度小于74才padding，所以并不会浪费很多。阈值也可以设置55，但是我听起来有点不自然。可能需要根据不同的模型，设置不同的阈值，我尝试了0-256的阈值
> 
> 请问你导出是int8量化么，int8量化后的模型有很明显的噪声你是怎么解决的

估计是fp16

**Comment by pengpengtao** [comment]
> > 30s是没有问题，具体多长没测试过，只要模型能支持的最大长度应该都能达到。如果文本过短确实会浪费token，但是浪费比较少，我测试了一个字的token和音频长度，然后设置的阈值是74，如果切段z_p的长度小于74才padding，所以并不会浪费很多。阈值也可以设置55，但是我听起来有点不自然。可能需要根据不同的模型，设置不同的阈值，我尝试了0-256的阈值
> 
> 请问你导出是int8量化么，int8量化后的模型有很明显的噪声你是怎么解决的

没试过int8，

**Comment by yuyun2000** [comment]
来活了！

**Comment by kikyou1234** [comment]
怎么联系

**Comment by Zer0TheObserver** [comment]
> 用了pad，比onnx快了4倍

大佬，您是怎么解决将onnx模型转换为固定输入的呢？我尝试过使用onnxslim简化，但是模型的某些节点仍然会保持动态。

**Comment by yuyun2000** [comment]
export的时候不要加动态轴

**Comment by pengpengtao** [comment]
哈哈哈，周末都在卷啊

**Comment by Zer0TheObserver** [comment]
> export的时候不要加动态轴

是指在把pth文件export成onnx的时候咩？

**Comment by pengpengtao** [comment]
> > export的时候不要加动态轴
> 
> 是指在把pth文件export成onnx的时候咩？

可以看看k2的onnx转vits，转了后再hf也有vits2转rknn的步骤，只不过哪个代码写得比较简单，但是大体步骤是正确的

**Comment by Zer0TheObserver** [comment]
> > > export的时候不要加动态轴
> > 
> > 
> > 是指在把pth文件export成onnx的时候咩？
> 
> 可以看看k2的onnx转vits，转了后再hf也有vits2转rknn的步骤，只不过哪个代码写得比较简单，但是大体步骤是正确的

感谢回答，请问k2指的是什么嘞？另外在huggingface没有看到vits转rknn的步骤，求仙人指路。

**Comment by yuyun2000** [comment]
kaldi2  sherpa-onnx

**Comment by pengpengtao** [comment]
> > > > export的时候不要加动态轴
> > > 
> > > 
> > > 是指在把pth文件export成onnx的时候咩？
> > 
> > 
> > 可以看看k2的onnx转vits，转了后再hf也有vits2转rknn的步骤，只不过哪个代码写得比较简单，但是大体步骤是正确的
> 
> 感谢回答，请问k2指的是什么嘞？另外在huggingface没有看到vits转rknn的步骤，求仙人指路。

https://huggingface.co/happyme531/Bert-VITS2-RKNN2，这个比较简陋，

**Comment by zzhdbw** [comment]
> > 是的，所以他是不太合适转rknn的
> 
> 我好像已经解决了，支持任意长度的文字输出音频

大佬怎么联系，能否有偿协助下？

**Comment by pengpengtao** [comment]
> > > 是的，所以他是不太合适转rknn的
> > 
> > 
> > 我好像已经解决了，支持任意长度的文字输出音频
> 
> 大佬怎么联系，能否有偿协助下？

1   wx:TpFlyy
