### ISSUE TITLE
onnx2rknn Numpy Version Error

### ISSUE THREAD

**Issue by Tianyun-Xuan** [airockchip/rknn-toolkit2#85]
我在尝试把Onnx模型转换成Rknn模型
我遇到了以下错误

I rknn-toolkit2 version: 2.0.0b0+9bab5682
--> Config model
done
--> Loading model
I It is recommended onnx opset 19, but your onnx model opset is 17!
I Model converted from pytorch, 'opset_version' should be set 19 in torch.onnx.export for successful convert!
I Loading : 100%|████████████████████████████████████████████████| 18/18 [00:00<00:00, 68821.76it/s]
done
--> Building model
D base_optimize ...
D base_optimize done.
D 
D fold_constant ...

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/demo/workspace/point-cloud-de-noising/src/onnx2rknn.py", line 74, in <module>
    main()
  File "/home/demo/workspace/point-cloud-de-noising/src/onnx2rknn.py", line 57, in main
    ret = rknn.build(do_quantization=QUANTIZE_ON)
  File "/home/demo/micromamba/envs/rknn/lib/python3.11/site-packages/rknn/api/rknn.py", line 201, in build
    return self.rknn_base.build(do_quantization=do_quantization, dataset=dataset, expand_batch_size=rknn_batch_size)
  File "/home/demo/micromamba/envs/rknn/lib/python3.11/site-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "/home/demo/micromamba/envs/rknn/lib/python3.11/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
AttributeError: _ARRAY_API not found
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError: <built-in function __import__> returned a result with an exception set
[1]    280625 segmentation fault  python3 src/onnx2rknn.py

**Comment by Tianyun-Xuan** [comment]
意识到是numpy版本的问题，我尝试将numpy 降级到1.24
但是遇到了 numpy bool 和 bool_的问题
我再次降级到 numpy1.23，为了配合环境我也降级到python3.9
但是仅仅在 from rknn.api import RKNN 时遇到了下面的报错
Traceback (most recent call last):
  File "/home/demo/workspace/point-cloud-de-noising/src/onnx2rknn.py", line 4, in <module>
    from rknn.api import RKNN # type: ignore
  File "/home/demo/micromamba/envs/rknn/lib/python3.9/site-packages/rknn/api/__init__.py", line 1, in <module>
    from rknn.api.rknn import RKNN
  File "/home/demo/micromamba/envs/rknn/lib/python3.9/site-packages/rknn/api/rknn.py", line 7, in <module>
    from .rknn_base import RKNNBase
  File "rknn/api/rknn_base.py", line 18, in init rknn.api.rknn_base
  File "rknn/api/quantizer.py", line 15, in init rknn.api.quantizer
  File "rknn/api/act_equalization.py", line 10, in init rknn.api.act_equalization
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/home/demo/micromamba/envs/rknn/lib/python3.9/site-packages/scipy/__init__.py", line 134, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/home/demo/micromamba/envs/rknn/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/demo/micromamba/envs/rknn/lib/python3.9/site-packages/scipy/stats/__init__.py", line 606, in <module>
    from ._stats_py import *
  File "/home/demo/micromamba/envs/rknn/lib/python3.9/site-packages/scipy/stats/_stats_py.py", line 49, in <module>
    from . import distributions
  File "/home/demo/micromamba/envs/rknn/lib/python3.9/site-packages/scipy/stats/distributions.py", line 11, in <module>
    from . import _discrete_distns
  File "/home/demo/micromamba/envs/rknn/lib/python3.9/site-packages/scipy/stats/_discrete_distns.py", line 10, in <module>
    from scipy.interpolate import interp1d
  File "/home/demo/micromamba/envs/rknn/lib/python3.9/site-packages/scipy/interpolate/__init__.py", line 167, in <module>
    from ._interpolate import *
  File "/home/demo/micromamba/envs/rknn/lib/python3.9/site-packages/scipy/interpolate/_interpolate.py", line 14, in <module>
    from . import _fitpack_py
  File "/home/demo/micromamba/envs/rknn/lib/python3.9/site-packages/scipy/interpolate/_fitpack_py.py", line 8, in <module>
    from ._fitpack_impl import bisplrep, bisplev, dblint  # noqa: F401
  File "/home/demo/micromamba/envs/rknn/lib/python3.9/site-packages/scipy/interpolate/_fitpack_impl.py", line 103, in <module>
    'iwrk': array([], dfitpack_int), 'u': array([], float),
TypeError

**Comment by Tianyun-Xuan** [comment]
再改用 python3.10 的whl + numpy1.24
出现以下报错
E RKNN: [14:40:48.150] Failed to config layer: 'Conv:/lila2/conv/conv/Conv', Fatal Error
E RKNN: [14:40:48.150] core_num 3 ori_Ih 126 ori_Iw 1198 ori_Ic 384 ori_Ib 1 
E RKNN: [14:40:48.150] ori_Kh 1 ori_Kw 1 ori_Kk 128 ori_Kc 384 ori_Ksx 1 ori_Ksy 1 
E RKNN: [14:40:48.150] ori_Oh 128 oriOw 1200 oriOc 128 pad_t 1 pad_b 1 pad_l 1 pad_r 1,
E RKNN: [14:40:48.150]  dilation_h 1 dilation_w 1 is_deconv 0,
E RKNN: [14:40:48.150] Please help report this bug!

**Comment by ythe2001** [comment]
请问onnx转rknn的代码是通用的吗？可以分享一份吗谢谢
